[package]
name = "deepgraph"
version = "0.1.0"
authors = ["Gary Hai <gary@neunit.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.31"
data-encoding = "2.2.1"
generational-arena = "0.2.8"
uuid = { version = "0.8.1", features = ["v4"] }